<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;


class gubernursseeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table('gubernurs')->insert([
            // Calon Gubernur di Provinsi Aceh
            [
                'nama' => 'Ahmad Fauzi',
                'jeniskelamin' => 'Laki-Laki',
                'ttl' => '05-05-1968',
                'agama' => 'Islam',
                'nama_w' => 'Siti Aisyah',
                'ttl_w' => '15-05-1968',
                'jeniskelamin_w' => 'Perempuan',
                'agama_w' => 'Islam',
                'idprovinsi' => 1,
                'visimisi' => 'Membangun Aceh yang sejahtera dan berkeadilan',
                'profil' => 'Ahmad Fauzi adalah seorang tokoh masyarakat yang dikenal...',
                'program' => '1. Meningkatkan perekonomian 2. Memperbaiki layanan kesehatan',
                'facebook' => 'https://www.facebook.com/sahal.maaghfud',
                'instagram' => 'https://www.instagram.com/stephanieeeflooo',
                'twitter' => 'https://twitter.com/CoachJustinL'
            ],
            [
                'nama' => 'Budi Santoso',
                'jeniskelamin' => 'Laki-Laki',
                'ttl' => '12-12-1972',
                'agama' => 'Islam',
                'nama_w' => 'Dewi Sartika',
                'ttl_w' => '15-05-1968',
                'jeniskelamin_w' => 'Perempuan',
                'agama_w' => 'Islam',
                'idprovinsi' => 1,
                'visimisi' => 'Aceh yang modern dan berdaya saing',
                'profil' => 'Budi Santoso telah berkarir di pemerintahan selama lebih dari 20 tahun...',
                'program' => '1. Peningkatan kualitas pendidikan 2. Pembangunan infrastruktur',
                'facebook' => 'https://www.facebook.com/sahal.maaghfud',
                'instagram' => 'https://www.instagram.com/stephanieeeflooo',
                'twitter' => 'https://twitter.com/CoachJustinL'
            ],
            // Calon Gubernur di Provinsi Bali
            [
                'nama' => 'Candra Wijaya',
                'jeniskelamin' => 'Laki-Laki',
                'ttl' => '15-03-1975',
                'agama' => 'Hindu',
                'nama_w' => 'Ayu Lestari',
                'ttl_w' => '15-05-1968',
                'jeniskelamin_w' => 'Perempuan',
                'agama_w' => 'Hindu',
                'idprovinsi' => 2,
                'visimisi' => 'Bali yang berbudaya dan maju',
                'profil' => 'Candra Wijaya memiliki pengalaman luas di bidang pariwisata...',
                'program' => '1. Promosi budaya 2. Peningkatan sektor pariwisata',
                'facebook' => 'https://www.facebook.com/sahal.maaghfud',
                'instagram' => 'https://www.instagram.com/stephanieeeflooo',
                'twitter' => 'https://twitter.com/CoachJustinL'
            ],
            [
                'nama' => 'Dewa Putu',
                'jeniskelamin' => 'Laki-Laki',
                'ttl' => '21-08-1980',
                'agama' => 'Hindu',
                'nama_w' => 'Made Ayu',
                'ttl_w' => '15-05-1968',
                'jeniskelamin_w' => 'Perempuan',
                'agama_w' => 'Hindu',
                'idprovinsi' => 2,
                'visimisi' => 'Mewujudkan Bali yang harmonis dan sejahtera',
                'profil' => 'Dewa Putu adalah seorang akademisi dan aktivis sosial...',
                'program' => '1. Pengembangan ekonomi kreatif 2. Peningkatan layanan kesehatan',
                'facebook' => 'https://www.facebook.com/sahal.maaghfud',
                'instagram' => 'https://www.instagram.com/stephanieeeflooo',
                'twitter' => 'https://twitter.com/CoachJustinL'
            ],
            // Calon Gubernur di Provinsi Banten
            [
                'nama' => 'Eko Prasetyo',
                'jeniskelamin' => 'Laki-Laki',
                'ttl' => '09-11-1970',
                'agama' => 'Islam',
                'nama_w' => 'Ani Susanti',
                'ttl_w' => '15-05-1968',
                'jeniskelamin_w' => 'Perempuan',
                'agama_w' => 'Islam',
                'idprovinsi' => 3,
                'visimisi' => 'Banten yang berdaya saing dan sejahtera',
                'profil' => 'Eko Prasetyo adalah seorang pengusaha sukses yang beralih ke politik...',
                'program' => '1. Pembangunan infrastruktur 2. Pengembangan UMKM',
                'facebook' => 'https://www.facebook.com/sahal.maaghfud',
                'instagram' => 'https://www.instagram.com/stephanieeeflooo',
                'twitter' => 'https://twitter.com/CoachJustinL'
            ],
            [
                'nama' => 'Fajar Sidik',
                'jeniskelamin' => 'Laki-Laki',
                'ttl' => '18-02-1973',
                'agama' => 'Islam',
                'nama_w' => 'Siti Rahma',
                'ttl_w' => '15-05-1968',
                'jeniskelamin_w' => 'Perempuan',
                'agama_w' => 'Islam',
                'idprovinsi' => 3,
                'visimisi' => 'Meningkatkan kualitas hidup masyarakat Banten',
                'profil' => 'Fajar Sidik telah mengabdi di pemerintahan selama lebih dari 15 tahun...',
                'program' => '1. Peningkatan layanan pendidikan 2. Pengentasan kemiskinan',
                'facebook' => 'https://www.facebook.com/sahal.maaghfud',
                'instagram' => 'https://www.instagram.com/stephanieeeflooo',
                'twitter' => 'https://twitter.com/CoachJustinL'
            ],
            // Calon Gubernur di Provinsi Bengkulu
            [
                'nama' => 'Gita Anjani',
                'jeniskelamin' => 'Perempuan',
                'ttl' => '25-04-1978',
                'agama' => 'Islam',
                'nama_w' => 'Rahmat Hidayat',
                'ttl_w' => '15-05-1968',
                'jeniskelamin_w' => 'Laki-Laki',
                'agama_w' => 'Islam',
                'idprovinsi' => 4,
                'visimisi' => 'Bengkulu yang ramah lingkungan dan maju',
                'profil' => 'Gita Anjani adalah seorang aktivis lingkungan dan pemimpin komunitas...',
                'program' => '1. Pelestarian lingkungan 2. Peningkatan kesejahteraan masyarakat',
                'facebook' => 'https://www.facebook.com/sahal.maaghfud',
                'instagram' => 'https://www.instagram.com/stephanieeeflooo',
                'twitter' => 'https://twitter.com/CoachJustinL'
            ],
            [
                'nama' => 'Hadi Susilo',
                'jeniskelamin' => 'Laki-Laki',
                'ttl' => '30-07-1982',
                'ttl_w' => '15-05-1968',
                'agama' => 'Islam',
                'nama_w' => 'Maya Sari',
                'jeniskelamin_w' => 'Perempuan',
                'agama_w' => 'Islam',
                'idprovinsi' => 4,
                'visimisi' => 'Membangun Bengkulu yang berdaya saing',
                'profil' => 'Hadi Susilo memiliki latar belakang di bidang ekonomi dan telah berkontribusi...',
                'program' => '1. Pengembangan ekonomi lokal 2. Peningkatan layanan kesehatan',
                'facebook' => 'https://www.facebook.com/sahal.maaghfud',
                'instagram' => 'https://www.instagram.com/stephanieeeflooo',
                'twitter' => 'https://twitter.com/CoachJustinL'
            ],
            // Calon Gubernur di Provinsi Gorontalo
            [
                'nama' => 'Iwan Setiawan',
                'jeniskelamin' => 'Laki-Laki',
                'ttl' => '11-06-1974',
                'agama' => 'Islam',
                'nama_w' => 'Sri Wahyuni',
                'ttl_w' => '15-05-1968',
                'jeniskelamin_w' => 'Perempuan',
                'agama_w' => 'Islam',
                'idprovinsi' => 5,
                'visimisi' => 'Membangun Gorontalo yang mandiri dan sejahtera',
                'profil' => 'Iwan Setiawan telah berkarir di bidang pendidikan dan memiliki dedikasi...',
                'program' => '1. Peningkatan kualitas pendidikan 2. Pengembangan infrastruktur',
                'facebook' => 'https://www.facebook.com/sahal.maaghfud',
                'instagram' => 'https://www.instagram.com/stephanieeeflooo',
                'twitter' => 'https://twitter.com/CoachJustinL'
            ],
            [
                'nama' => 'Joko Susanto',
                'jeniskelamin' => 'Laki-Laki',
                'ttl' => '19-09-1976',
                'agama' => 'Islam',
                'nama_w' => 'Indah Permata',
                'ttl_w' => '15-05-1968',
                'jeniskelamin_w' => 'Perempuan',
                'agama_w' => 'Islam',
                'idprovinsi' => 5,
                'visimisi' => 'Gorontalo yang maju dan berkeadilan',
                'profil' => 'Joko Susanto adalah seorang pengusaha yang sukses di bidang agribisnis...',
                'program' => '1. Peningkatan sektor pertanian 2. Pengembangan ekonomi kreatif',
                'facebook' => 'https://www.facebook.com/sahal.maaghfud',
                'instagram' => 'https://www.instagram.com/stephanieeeflooo',
                'twitter' => 'https://twitter.com/CoachJustinL'
            ],
            // Calon Gubernur di Provinsi Jambi
            [
                'nama' => 'Kurniawan',
                'jeniskelamin' => 'Laki-Laki',
                'ttl' => '03-02-1975',
                'agama' => 'Islam',
                'nama_w' => 'Novianti',
                'ttl_w' => '15-05-1968',
                'jeniskelamin_w' => 'Perempuan',
                'agama_w' => 'Islam',
                'idprovinsi' => 6,
                'visimisi' => 'Jambi yang makmur dan sejahtera',
                'profil' => 'Kurniawan adalah seorang birokrat yang telah mengabdi di pemerintahan...',
                'program' => '1. Peningkatan pelayanan publik 2. Pembangunan infrastruktur',
                'facebook' => 'https://www.facebook.com/sahal.maaghfud',
                'instagram' => 'https://www.instagram.com/stephanieeeflooo',
                'twitter' => 'https://twitter.com/CoachJustinL'
            ],
            [
                'nama' => 'Lukman Hakim',
                'jeniskelamin' => 'Laki-Laki',
                'ttl' => '14-07-1973',
                'agama' => 'Islam',
                'nama_w' => 'Siti Nurhayati',
                'ttl_w' => '15-05-1968',
                'jeniskelamin_w' => 'Perempuan',
                'agama_w' => 'Islam',
                'idprovinsi' => 6,
                'visimisi' => 'Jambi yang adil dan berdaya saing',
                'profil' => 'Lukman Hakim adalah seorang akademisi dan peneliti yang fokus pada pembangunan...',
                'program' => '1. Pengentasan kemiskinan 2. Pengembangan sektor pendidikan',
                'facebook' => 'https://www.facebook.com/sahal.maaghfud',
                'instagram' => 'https://www.instagram.com/stephanieeeflooo',
                'twitter' => 'https://twitter.com/CoachJustinL'
            ],
            // Calon Gubernur di Provinsi Jawa Barat
            [
                'nama' => 'Mulyadi',
                'jeniskelamin' => 'Laki-Laki',
                'ttl' => '01-01-1968',
                'agama' => 'Islam',
                'nama_w' => 'Rahmi',
                'ttl_w' => '15-05-1968',
                'jeniskelamin_w' => 'Perempuan',
                'agama_w' => 'Islam',
                'idprovinsi' => 7,
                'visimisi' => 'Jawa Barat yang maju dan berkeadilan',
                'profil' => 'Mulyadi adalah seorang tokoh masyarakat yang dikenal...',
                'program' => '1. Meningkatkan perekonomian 2. Memperbaiki layanan kesehatan',
                'facebook' => 'https://www.facebook.com/sahal.maaghfud',
                'instagram' => 'https://www.instagram.com/stephanieeeflooo',
                'twitter' => 'https://twitter.com/CoachJustinL'
            ],
            [
                'nama' => 'Nugroho',
                'jeniskelamin' => 'Laki-Laki',
                'ttl' => '12-12-1972',
                'agama' => 'Islam',
                'nama_w' => 'Desi',
                'ttl_w' => '15-05-1968',
                'jeniskelamin_w' => 'Perempuan',
                'agama_w' => 'Islam',
                'idprovinsi' => 7,
                'visimisi' => 'Jawa Barat yang modern dan berdaya saing',
                'profil' => 'Nugroho telah berkarir di pemerintahan selama lebih dari 20 tahun...',
                'program' => '1. Peningkatan kualitas pendidikan 2. Pembangunan infrastruktur',
                'facebook' => 'https://www.facebook.com/sahal.maaghfud',
                'instagram' => 'https://www.instagram.com/stephanieeeflooo',
                'twitter' => 'https://twitter.com/CoachJustinL'
            ],
            // Calon Gubernur di Provinsi Jawa Tengah
            [
                'nama' => 'Oka Suhendra',
                'jeniskelamin' => 'Laki-Laki',
                'ttl' => '05-05-1968',
                'agama' => 'Islam',
                'nama_w' => 'Ratna',
                'ttl_w' => '15-05-1968',
                'jeniskelamin_w' => 'Perempuan',
                'agama_w' => 'Islam',
                'idprovinsi' => 8,
                'visimisi' => 'Jawa Tengah yang sejahtera dan berkeadilan',
                'profil' => 'Oka Suhendra adalah seorang tokoh masyarakat yang dikenal...',
                'program' => '1. Meningkatkan perekonomian 2. Memperbaiki layanan kesehatan',
                'facebook' => 'https://www.facebook.com/sahal.maaghfud',
                'instagram' => 'https://www.instagram.com/stephanieeeflooo',
                'twitter' => 'https://twitter.com/CoachJustinL'
            ],
            [
                'nama' => 'Pandu Wijaya',
                'jeniskelamin' => 'Laki-Laki',
                'ttl' => '12-12-1972',
                'agama' => 'Islam',
                'nama_w' => 'Santi',
                'ttl_w' => '15-05-1968',
                'jeniskelamin_w' => 'Perempuan',
                'agama_w' => 'Islam',
                'idprovinsi' => 8,
                'visimisi' => 'Jawa Tengah yang modern dan berdaya saing',
                'profil' => 'Pandu Wijaya telah berkarir di pemerintahan selama lebih dari 20 tahun...',
                'program' => '1. Peningkatan kualitas pendidikan 2. Pembangunan infrastruktur',
                'facebook' => 'https://www.facebook.com/sahal.maaghfud',
                'instagram' => 'https://www.instagram.com/stephanieeeflooo',
                'twitter' => 'https://twitter.com/CoachJustinL'
            ],
            // Calon Gubernur di Provinsi Jawa Timur
            [
                'nama' => 'Rama Wijaya',
                'jeniskelamin' => 'Laki-Laki',
                'ttl' => '05-05-1968',
                'agama' => 'Islam',
                'nama_w' => 'Sari',
                'ttl_w' => '15-05-1968',
                'jeniskelamin_w' => 'Perempuan',
                'agama_w' => 'Islam',
                'idprovinsi' => 9,
                'visimisi' => 'Jawa Timur yang sejahtera dan berkeadilan',
                'profil' => 'Rama Wijaya adalah seorang tokoh masyarakat yang dikenal...',
                'program' => '1. Meningkatkan perekonomian 2. Memperbaiki layanan kesehatan',
                'facebook' => 'https://www.facebook.com/sahal.maaghfud',
                'instagram' => 'https://www.instagram.com/stephanieeeflooo',
                'twitter' => 'https://twitter.com/CoachJustinL'
            ],
            [
                'nama' => 'Setyo Wibowo',
                'jeniskelamin' => 'Laki-Laki',
                'ttl' => '12-12-1972',
                'agama' => 'Islam',
                'nama_w' => 'Mira',
                'ttl_w' => '15-05-1968',
                'jeniskelamin_w' => 'Perempuan',
                'agama_w' => 'Islam',
                'idprovinsi' => 9,
                'visimisi' => 'Jawa Timur yang modern dan berdaya saing',
                'profil' => 'Setyo Wibowo telah berkarir di pemerintahan selama lebih dari 20 tahun...',
                'program' => '1. Peningkatan kualitas pendidikan 2. Pembangunan infrastruktur',
                'facebook' => 'https://www.facebook.com/sahal.maaghfud',
                'instagram' => 'https://www.instagram.com/stephanieeeflooo',
                'twitter' => 'https://twitter.com/CoachJustinL'
            ],
            // Calon Gubernur di Provinsi Kalimantan Barat
            [
                'nama' => 'Teguh Santoso',
                'jeniskelamin' => 'Laki-Laki',
                'ttl' => '05-05-1968',
                'agama' => 'Islam',
                'nama_w' => 'Lina',
                'ttl_w' => '15-05-1968',
                'jeniskelamin_w' => 'Perempuan',
                'agama_w' => 'Islam',
                'idprovinsi' => 10,
                'visimisi' => 'Kalimantan Barat yang sejahtera dan berkeadilan',
                'profil' => 'Teguh Santoso adalah seorang tokoh masyarakat yang dikenal...',
                'program' => '1. Meningkatkan perekonomian 2. Memperbaiki layanan kesehatan',
                'facebook' => 'https://www.facebook.com/sahal.maaghfud',
                'instagram' => 'https://www.instagram.com/stephanieeeflooo',
                'twitter' => 'https://twitter.com/CoachJustinL'
            ],
            [
                'nama' => 'Usman Hakim',
                'jeniskelamin' => 'Laki-Laki',
                'ttl' => '12-12-1972',
                'agama' => 'Islam',
                'nama_w' => 'Sari',
                'ttl_w' => '15-05-1968',
                'jeniskelamin_w' => 'Perempuan',
                'agama_w' => 'Islam',
                'idprovinsi' => 10,
                'visimisi' => 'Kalimantan Barat yang modern dan berdaya saing',
                'profil' => 'Usman Hakim telah berkarir di pemerintahan selama lebih dari 20 tahun...',
                'program' => '1. Peningkatan kualitas pendidikan 2. Pembangunan infrastruktur',
                'facebook' => 'https://www.facebook.com/sahal.maaghfud',
                'instagram' => 'https://www.instagram.com/stephanieeeflooo',
                'twitter' => 'https://twitter.com/CoachJustinL'
            ]
        ]);
    }
}
